# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Kong | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'kong'
    - 'kong-package'
    - 'kong-configure'
    - 'kong-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Kong | Define whether Kong is prepared.'
  become: yes
  stat:
    path: '{{ kong_prefix_path }}'
  register: 'kong_prepared'
  tags:
    - 'kong'
    - 'kong-package'
    - 'kong-configure'
    - 'kong-service'
    - 'package'
    - 'configure'
    - 'service'

- import_tasks: 'package.yml'
  tags:
    - 'kong'
    - 'kong-package'
    - 'package'

- import_tasks: 'configure.yml'
  tags:
    - 'kong'
    - 'kong-configure'
    - 'configure'

- import_tasks: 'service.yml'
  tags:
    - 'kong'
    - 'kong-service'
    - 'service'